README.md

iOS-26 Added initialize SDK information to Read.me file

iOS-26 Added initialize SDK to Read.me file

---

Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Core/Show/Models/EventData.swift
Sources/Talkshoplive/Resources/Keys/env.json
Sources/Talkshoplive/Utils/Networking/Networking.swift
Tests/TalkshopliveTests/ProviderTests/ChatTests.swift

iOS-20 Chat Module - Subscribe Channels

iOS-20 Chat Module - Subscribe Channels

---

Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Tests/TalkshopliveTests/ProviderTests/ChatTests.swift

IOS-21 Chat Module - UnSubscribe Channels

IOS-21 Chat Module - UnSubscribe Channels

---

README.md
Sources/Talkshoplive/Core/Authentication/TalkShopLive.swift
Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Utils/Helpers/Config.swift
Sources/Talkshoplive/Utils/Networking/APIHandler.swift
Sources/Talkshoplive/Utils/Networking/Networking.swift
Sources/Talkshoplive/Utils/Networking/Response.swift
Sources/Talkshoplive/Utils/Networking/Urls.swift
Tests/TalkshopliveTests/ProviderTests/ChatTests.swift

iOS-33 Federated User Authentication token and Pubnub Keys
* Managed JWT param in initializeChat function to differentiate its guest or fedarated user
* Guest user token API integrated
* fedrated user token API integrated
* Assign response's keys and data to initialize pubnub

 iOS-33 Created user token 

---

Package.swift
Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Tests/TalkshopliveTests/ProviderTests/ChatTests.swift

[iOS-SDK]: Add PubNub event listeners - Part 1

[iOS-SDK]: Add PubNub event listeners - Part 1

---

README.md
Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Core/Chat/Model/ChatModel.swift
Sources/Talkshoplive/Core/Chat/Model/MessageData.swift
Sources/Talkshoplive/Core/Show/Show.swift
Sources/Talkshoplive/Core/Show/ShowProvider.swift
Sources/Talkshoplive/Utils/Helpers/Date_Extension.swift
Sources/Talkshoplive/Utils/Helpers/TalkShopLive_Extension.swift
Sources/Talkshoplive/Utils/Networking/Networking.swift
Sources/Talkshoplive/Utils/Networking/Urls.swift
Tests/TalkshopliveTests/ServicesTests/ShowTests.swift

IOS-28 Chat - Send message
- Read me file updated
- Added recieved message custom listener
- Managed object for send message from sdk
- Chat-Init() Removed params mode and refresh
- Show - getStatus(showId) - Updated param to showKey

IOS-28 Chat - Send message

---

Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift

IOS-28 Chat : Added Custom listener for recieve new message

IOS-28 Chat : Custom listeners

---

Sources/Talkshoplive/Core/Chat/ChatProvider.swift

IOS-28 Chat - Send message
- Managed validation for max length 200
- Managed for message type

IOS-28 Chat Send message - Validation

---

README.md
Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Core/Show/Models/EventData.swift
Sources/Talkshoplive/Core/Show/Models/ShowData.swift
Sources/Talkshoplive/Core/Show/Show.swift
Sources/Talkshoplive/Core/Show/ShowProvider.swift
Sources/Talkshoplive/Resources/Keys/Staging.json
Sources/Talkshoplive/Utils/Helpers/Date_Extension.swift
Sources/Talkshoplive/Utils/Networking/APIHandler.swift
Sources/Talkshoplive/Utils/Networking/Networking.swift
Sources/Talkshoplive/Utils/Networking/Urls.swift
Tests/TalkshopliveTests/ProviderTests/ChatTests.swift
Tests/TalkshopliveTests/ServicesTests/ShowTests.swift

IOS : Shows minor fixes
- Managed hsl_playback_url, trailer_url and status
- when response null, empty instance will return.
- getDetails - param name updated to showKey.
- If debug mode true, console logs will be there, else required logs will be there

IOS : Shows minor fixes

---

Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Core/Chat/Model/MessageData.swift
Sources/Talkshoplive/Core/Show/Models/ShowData.swift

IOS-Chat:Send message
- added name param to sender details while sending message.
- fixes for showData->airDate

IOS-Chat:Send message fixes

---

Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Core/Show/Models/EventData.swift
Sources/Talkshoplive/Core/Show/Models/ShowData.swift
Sources/Talkshoplive/Utils/Networking/Response.swift

IOS-32 Show : Added additional fields
- Added Channel_name, channel_logo, show_description, video_thumbnail_url, trailer_duration

IOS-32 Show : Added additional fields

---

README.md

IOS-22  Fetch chat history Part-1 : Read me file updated

IOS-22  chat history Part-1 : Read me file updated 

---

Sources/Talkshoplive/Core/Show/Models/EventData.swift

iOS-44 Additional field for `show.getStatus`:  streamInCloud

 iOS-44 Additional field for `show.getStatus`:  streamInCloud

---

Sources/Talkshoplive/Core/Chat/Model/MessageData.swift

IOS-Chat : Sender object fixed
- Fixed issue for if sender is coming as string/object , needs to decode in both cases

IOS-Chat : Sender object fixed

---

Sources/Talkshoplive/Core/Chat/Model/MessageData.swift

MessageData
- sender : Added profileURL
- made public all the keys accessible

MessageData : Added sender profileUrl

---

Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Core/Chat/Model/MessageData.swift

iOS-Chat New message type fixes

iOS-Chat New message type fixes

---

README.md
Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift

- Created private and public method 
- Updated read.me

IOS-48 : Chat - Count Messages

---

Sources/Talkshoplive/Core/Show/Models/EventData.swift

Added totalViews key to get total viewers count

iOS-40 Show : Get Total Viewers

---

README.md
Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Utils/Networking/APIHandler.swift
Sources/Talkshoplive/Utils/Networking/Networking.swift

- For wrong showKey getStatus should throw error not an empty object
- Chat Init with wrong showKey should throw an error for messaging token.

iOS-52 : Fixes for shows and chat errors

---

README.md
Sources/Talkshoplive/Core/Authentication/TalkShopLive.swift
Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Core/Show/Models/EventData.swift
Sources/Talkshoplive/Core/Show/Models/ShowData.swift
Sources/Talkshoplive/Core/Show/Show.swift
Sources/Talkshoplive/Resources/Keys/Production.json
Sources/Talkshoplive/Resources/Keys/Staging.json
Sources/Talkshoplive/Utils/Collector.swift
Sources/Talkshoplive/Utils/Helpers/Config.swift
Sources/Talkshoplive/Utils/Helpers/Date_Extension.swift
Sources/Talkshoplive/Utils/Networking/APIHandler.swift
Sources/Talkshoplive/Utils/Networking/Networking.swift
Sources/Talkshoplive/Utils/Networking/Request.swift
Sources/Talkshoplive/Utils/Networking/Response.swift
Sources/Talkshoplive/Utils/Networking/Urls.swift

Added analytics for sdk initialize, chat-init, chat-updateuser, show-getDetails

IOS-49 Collecor

---

Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Core/Chat/Model/MessageData.swift
Sources/Talkshoplive/Core/User/Users.swift
Sources/Talkshoplive/Core/User/UsersProvider.swift
Sources/Talkshoplive/Utils/Helpers/TalkShopLive_Extension.swift
Sources/Talkshoplive/Utils/Networking/APIHandler.swift
Sources/Talkshoplive/Utils/Networking/Networking.swift
Sources/Talkshoplive/Utils/Networking/Response.swift
Sources/Talkshoplive/Utils/Networking/Urls.swift

* API integrated to get sender information in history
* Stored sender information locally
* When recieve new message, add sender information

IOS-41 Chat history Part -2

---

Sources/Talkshoplive/Core/Authentication/TalkShopLive.swift
Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Core/Show/Show.swift
Sources/Talkshoplive/Core/Show/ShowProvider.swift
Sources/Talkshoplive/Core/User/Users.swift
Sources/Talkshoplive/Core/User/UsersProvider.swift
Sources/Talkshoplive/Utils/Collector.swift
Sources/Talkshoplive/Utils/Networking/APIHandler.swift
Sources/Talkshoplive/Utils/Networking/ErrorCodes.swift
Sources/Talkshoplive/Utils/Networking/Networking.swift

- Added error codes
- Managed to setup and return it
- Updated completion for error to APIClientError

IOS-50 Error Codes

---

Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Utils/Helpers/Date_Extension.swift

- Passed start timetoken by default
- Sorted final messages

IOS-Chat : Fixes for chat history 

---

Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Utils/Networking/ErrorCodes.swift

1. Error code Added : CHAT_TIMEOUT, SHOW_NOT_LIVE , 
2. Fetch history : Issue fixed to return nil when history ended

IOS-68 Error code Added, Fetch history issue fixed

---

README.md
Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Utils/Networking/Request.swift

Updated ‘Category' Value and ‘video_time' Key 
- SELECT_VIEW_SHOW_DETAILS -> SELECT_SHOW_METADATA
- video_time -> total_event_duration

IOS-66 : Collector fixes

---

README.md
Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Core/Show/Show.swift
Sources/Talkshoplive/Utils/Networking/APIHandler.swift
Sources/Talkshoplive/Utils/Networking/ErrorCodes.swift
Sources/Talkshoplive/Utils/Networking/Networking.swift

* Added logs with class name 
* Added logs with TSL where needed

IOS-71 : Error code logging updated

---

README.md
Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Core/Chat/Model/MessageData.swift
Sources/Talkshoplive/Utils/Networking/ErrorCodes.swift
Sources/Talkshoplive/Utils/Networking/Networking.swift
Sources/Talkshoplive/Utils/Networking/Urls.swift

- Liked comment using pubnub
- OnLikeComment custom listener
- Unliked comment using backend
- OnUnlikeComment custom listener

IOS-78 Like/Unlike Comment

---

Sources/Talkshoplive/Utils/Collector.swift

- Updated sdk version from 1.0.5 to 2.0.0

IOS-99 Release 2.0.0 

---

Package.swift
Sources/Talkshoplive/Utils/Helpers/TalkShopLive_Extension.swift

- Made changes to support UIKit

IOS-112 Minor changes for release 2.0.1

---

Sources/Talkshoplive/Utils/Helpers/Config.swift

IOS-124 Updated collector endpoint

IOS-124 Updated collector endpoint

---

Sources/Talkshoplive/Core/Show/Models/EventData.swift
Sources/Talkshoplive/Utils/Networking/Networking.swift
Sources/Talkshoplive/Utils/Networking/Urls.swift

- Updated EventData Model
- Updated show's get current endpoint

[IOS-115] Show 2.0 changes for Show -> getCurrent

---

README.md
Sources/Talkshoplive/Core/Show/Show.swift
Sources/Talkshoplive/Utils/Collect.swift

- Updated collect defination
- Updated show instance to use inside sdk when triggering collector actions
- Updated sdk version - 3.0.0

[IOS-137] Updated collector.collect definition with event instance

---

.gitignore
Sources/Talkshoplive/Core/Chat/Chat.swift
Sources/Talkshoplive/Core/Chat/ChatProvider.swift
Sources/Talkshoplive/Core/Show/Models/Asset.swift
Sources/Talkshoplive/Core/Show/Models/EventData.swift
Sources/Talkshoplive/Core/Show/Models/ShowData.swift
Sources/Talkshoplive/Utils/Networking/APIHandler.swift
Sources/Talkshoplive/Utils/Networking/Networking.swift

* Added thumbnail to asset types
* Simplified assets object decoding to use only necessary fields
* Minor fixes for debug logs
* Fixed decoding issues

[IOS-144] Shows 2.0: Update and simplify assets object decoding

---

README.md
Sources/Talkshoplive/Core/Show/Models/ProductData.swift
Sources/Talkshoplive/Utils/Collect.swift
Sources/Talkshoplive/Utils/Networking/Networking.swift
Sources/Talkshoplive/Utils/Networking/Request.swift

- Updated productdata model
- Managed for getting variantID
- Updated collect defination and related functions call

[iOS-154] Collector : Added productKey and variantId in payload

---

Package.swift

- Tested Pubnub all the functions used in SDK
- Tested Live chat - send/delete/like/dislike
- Tested by genearting xc framework

IOS-158  Upgraded Pubnub 9.3.0
